services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command:
      sh -c "python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
